version: '3.8'
services: 
  app:
    image: tomrosert/wp-codespace:latest
    restart: unless-stopped
    volumes:
      - ../..:/workspaces:cached
    command: 
      sleep infinity
    ports:
      - "8080:80"
  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - ../../mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  phpmyadmin:
    environment:
      PMA_HOST: db
      PMA_DATABASE: wordpress
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
      UPLOAD_LIMIT: 1024M
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 8081:80
